dist: xenial
language: node_js

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: lint
      script: npm run lint
      node_js: "14"
    - stage: unit tests
      script: npm test
      node_js: "12"
    - node_js: "14"
    - node_js: "15"
    - stage: coverage
      script: npm run coverage
      node_js: "14"

# NOTE: This is unused atm
# notifications:
#    webhooks:
#        urls:
#            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MEhhbGYtU2hvdCUzQWhhbGYtc2hvdC51ay8lMjFxUE5PblVzTnNaclRvRlpxeEIlM0FoYWxmLXNob3QudWs"
#        on_success: change  # always|never|change
#        on_failure: always
#        on_start: never
